version: '3.0'

services:
 backend:
  build: backend
  command: node build/server.js
  expose:
  - "3000"
  networks:
  - backend
  - frontend
  environment:
    - DATABASE_URL=mongodb://database:27017
    - ENV=prod

 database:
  image: mongo
  expose:
  - "27017"
  networks:
  - backend

 frontend:
  build: frontend
  ports:
  - "80:80"
  networks:
  - frontend
  depends_on:
  - backend
  
networks:
  backend:
  frontend: